version: 2

# sources:
#   - name: raw
#     schema: main
#     tables:
#       - name: yellow_tripdata
#         description: "NYC Yellow Taxi trips in Parquet format."
#         external:
#           external_table: true
#           location: "../../data/raw/yellow_tripdata_*.parquet"
#           format: "parquet"
